import { FormEvent } from 'react';
import { Icon } from '@iconify/react';
import { ProductImageUpload } from './ProductImageUpload';

export type AddProductFormState = {
  sku: string;
  nameAr: string;
  nameEn: string;
  descriptionAr: string;
  descriptionEn: string;
  price: string;
  stockQuantity: string;
  categoryId: string;
  isFeatured: boolean;
};

interface CategoryOption {
  id: string;
  nameAr: string;
}

interface AddProductFormProps {
  form: AddProductFormState;
  onChange: (form: AddProductFormState) => void;
  imageFiles: File[];
  onImageFilesChange: (files: File[]) => void;
  cloudinaryEnabled: boolean;
  categories: CategoryOption[];
  error: string;
  saving: boolean;
  onSubmit: (e: FormEvent) => void;
  onCancel?: () => void;
  compact?: boolean;
  submitLabel?: string;
  showImageUpload?: boolean;
  maxImages?: number;
  headerTitle?: string;
  headerHint?: string;
  /** Show SKU field (edit mode). Hidden on create — SKU is generated by the API. */
  showSku?: boolean;
}

export function AddProductForm({
  form,
  onChange,
  categories,
  error,
  saving,
  imageFiles,
  onImageFilesChange,
  cloudinaryEnabled,
  onSubmit,
  onCancel,
  compact,
  submitLabel = 'نشر المنتج',
  showImageUpload = true,
  maxImages = 10,
  headerTitle = 'إضافة منتج للمتجر',
  headerHint = 'املأ الحقول المطلوبة (*) ثم احفظ. يظهر في المتجر عند تفعيله.',
  showSku = false,
}: AddProductFormProps) {
  const set = (key: keyof AddProductFormState, value: string) =>
    onChange({ ...form, [key]: value });

  return (
    <form onSubmit={onSubmit} className={compact ? 'space-y-4' : 'space-y-6'}>
      {!compact && (
        <div className="flex items-start gap-3 rounded-xl border border-primary/20 bg-primary-50/50 p-4">
          <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary text-white">
            <Icon icon="mdi:package-variant-plus" className="text-xl" />
          </span>
          <div className="text-sm">
            <p className="font-semibold text-primary-800">{headerTitle}</p>
            <p className="mt-0.5 text-slate-600">{headerHint}</p>
          </div>
        </div>
      )}

      <fieldset className="space-y-4">
        <legend className="text-sm font-bold text-slate-800">١ — التعريف</legend>
        <div className="grid gap-4 sm:grid-cols-2">
          {showSku ? (
            <label className="block">
              <span className="mb-1 block text-xs font-medium text-slate-600">رمز SKU</span>
              <input
                className="input-field font-mono"
                placeholder="مثال: HD-025"
                value={form.sku}
                onChange={(e) => set('sku', e.target.value)}
              />
            </label>
          ) : (
            <div className="flex items-center gap-2 rounded-xl border border-brand-sand bg-brand-cream/60 px-3 py-2.5 text-xs text-slate-600 sm:col-span-2">
              <Icon icon="mdi:barcode-scan" className="shrink-0 text-lg text-brand-green" />
              <span>يُنشأ رمز SKU تلقائياً من التصنيف عند الحفظ (مثال: CLEAN-0001)</span>
            </div>
          )}
          <label className={`block ${showSku ? '' : 'sm:col-span-2'}`}>
            <span className="mb-1 block text-xs font-medium text-slate-600">
              التصنيف <span className="text-red-600">*</span>
            </span>
            <select
              required
              className="select-field"
              value={form.categoryId}
              onChange={(e) => set('categoryId', e.target.value)}
            >
              <option value="">— اختر تصنيفاً —</option>
              {categories.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.nameAr}
                </option>
              ))}
            </select>
            {categories.length === 0 && (
              <p className="mt-1 text-xs text-amber-700">أنشئ تصنيفاً أولاً من صفحة التصنيفات.</p>
            )}
          </label>
          <label className="block">
            <span className="mb-1 block text-xs font-medium text-slate-600">
              الاسم بالعربية <span className="text-red-600">*</span>
            </span>
            <input
              required
              className="input-field"
              value={form.nameAr}
              onChange={(e) => set('nameAr', e.target.value)}
            />
          </label>
          <label className="block">
            <span className="mb-1 block text-xs font-medium text-slate-600">
              الاسم بالإنجليزية <span className="text-red-600">*</span>
            </span>
            <input
              required
              className="input-field"
              dir="ltr"
              value={form.nameEn}
              onChange={(e) => set('nameEn', e.target.value)}
            />
          </label>
        </div>
      </fieldset>

      <fieldset className="space-y-4">
        <legend className="text-sm font-bold text-slate-800">٢ — الوصف (اختياري)</legend>
        <div className="grid gap-4">
          <label className="block">
            <span className="mb-1 block text-xs font-medium text-slate-600">الوصف بالعربية</span>
            <textarea
              className="input-field min-h-[120px] resize-y"
              placeholder="تفاصيل المنتج، الاستخدام، الحجم..."
              value={form.descriptionAr}
              onChange={(e) => set('descriptionAr', e.target.value)}
            />
          </label>
          <label className="block">
            <span className="mb-1 block text-xs font-medium text-slate-600">الوصف بالإنجليزية</span>
            <textarea
              className="input-field min-h-[100px] resize-y"
              dir="ltr"
              placeholder="Product details, usage, size..."
              value={form.descriptionEn}
              onChange={(e) => set('descriptionEn', e.target.value)}
            />
          </label>
        </div>
      </fieldset>

      <fieldset className="space-y-4">
        <legend className="text-sm font-bold text-slate-800">٣ — السعر والمخزون</legend>
        <div className="grid gap-4 sm:grid-cols-2">
          <label className="block">
            <span className="mb-1 block text-xs font-medium text-slate-600">
              السعر (د.أ) <span className="text-red-600">*</span>
            </span>
            <input
              required
              type="number"
              min="0"
              step="0.001"
              className="input-field"
              dir="ltr"
              value={form.price}
              onChange={(e) => set('price', e.target.value)}
            />
          </label>
          <label className="block">
            <span className="mb-1 block text-xs font-medium text-slate-600">
              الكمية في المخزون <span className="text-red-600">*</span>
            </span>
            <input
              required
              type="number"
              min="0"
              className="input-field"
              dir="ltr"
              value={form.stockQuantity}
              onChange={(e) => set('stockQuantity', e.target.value)}
            />
          </label>
        </div>
        <label className="flex cursor-pointer items-start gap-3 rounded-xl border border-amber-200/80 bg-amber-50/50 p-4 sm:col-span-2">
          <input
            type="checkbox"
            className="table-checkbox mt-0.5"
            checked={form.isFeatured}
            onChange={(e) => onChange({ ...form, isFeatured: e.target.checked })}
          />
          <span className="text-sm">
            <span className="flex items-center gap-1.5 font-bold text-slate-900">
              <Icon icon="mdi:star" className="text-amber-600" />
              منتج مميز
            </span>
            <span className="mt-0.5 block text-xs text-slate-600">
              يظهر في قسم «منتجات مميزة» على الصفحة الرئيسية (حتى 8 منتجات)
            </span>
          </span>
        </label>
      </fieldset>

      {showImageUpload && (
        <fieldset className="space-y-4">
          <legend className="text-sm font-bold text-slate-800">٤ — صور المنتج (اختياري)</legend>
          <ProductImageUpload
            files={imageFiles}
            onChange={onImageFilesChange}
            disabled={saving}
            cloudinaryEnabled={cloudinaryEnabled}
            maxImages={maxImages}
          />
        </fieldset>
      )}

      {error && (
        <p className="flex items-center gap-2 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">
          <Icon icon="mdi:alert-circle-outline" />
          {error}
        </p>
      )}

      <div className="flex flex-wrap gap-3 border-t border-slate-100 pt-4">
        <button type="submit" disabled={saving || categories.length === 0} className="btn-primary min-w-[10rem]">
          <Icon icon="mdi:check-circle-outline" className="text-lg" />
          {saving ? 'جاري الحفظ...' : submitLabel}
        </button>
        {onCancel && (
          <button type="button" onClick={onCancel} className="btn-secondary">
            إلغاء
          </button>
        )}
      </div>
    </form>
  );
}

export const emptyProductForm = (): AddProductFormState => ({
  sku: '',
  nameAr: '',
  nameEn: '',
  descriptionAr: '',
  descriptionEn: '',
  price: '',
  stockQuantity: '0',
  categoryId: '',
  isFeatured: false,
});
