/**
 * Catalog seed data — realistic Jordan daily-use products.
 * Images use CDN URLs verified to return HTTP 200 (dummyjson + picsum + select Unsplash).
 */

const PICSUM = (slug: string) => `https://picsum.photos/seed/abounas-${slug}/800/800`;
const DJ = (path: string) => `https://cdn.dummyjson.com/product-images/${path}/thumbnail.webp`;

export type SeedProduct = {
  sku: string;
  slug: string;
  nameAr: string;
  nameEn: string;
  descriptionAr: string;
  descriptionEn: string;
  price: number;
  compareAtPrice?: number;
  stock: number;
  featured: boolean;
  categorySlug: 'cleaning' | 'kitchen' | 'home-essentials' | 'bathroom';
  image: string;
  tagSlugs: ('best-seller' | 'new')[];
};

export const SEED_CATALOG_PRODUCTS: SeedProduct[] = [
  {
    sku: 'HD-001',
    slug: 'dish-soap-lemon-750ml',
    nameAr: 'سائل جلي ليمون 750 مل — أبو النص',
    nameEn: 'Lemon Dish Soap 750ml',
    descriptionAr: 'سائل جلي مركز برائحة الليمون، يزيل الدهون بسرعة ومناسب للأيدي الحساسة. يكفي حوالي 150 رشة.',
    descriptionEn: 'Concentrated lemon dish soap, tough on grease, gentle on hands.',
    price: 2.49,
    compareAtPrice: 2.99,
    stock: 180,
    featured: true,
    categorySlug: 'cleaning',
    image: DJ('groceries/juice'),
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'HD-002',
    slug: 'multi-surface-cleaner-1l',
    nameAr: 'منظف متعدد الأسطح 1 لتر',
    nameEn: 'Multi-Surface Cleaner 1L',
    descriptionAr: 'منظف عملي للمطبخ والحمام والسيراميك. رائحة منعشة ولا يترك آثاراً.',
    descriptionEn: 'All-purpose cleaner for kitchen, bathroom, and tiles.',
    price: 3.75,
    stock: 95,
    featured: true,
    categorySlug: 'cleaning',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    tagSlugs: ['best-seller', 'new'],
  },
  {
    sku: 'HD-003',
    slug: 'kitchen-towels-3-roll',
    nameAr: 'مناديل مطبخ — 3 لفات',
    nameEn: 'Kitchen Paper Towels 3-Pack',
    descriptionAr: 'مناديل مطبخ عالية الامتصاص، مناسبة للتجفيف والتنظيف اليومي.',
    descriptionEn: 'Absorbent kitchen rolls for daily cleaning and drying.',
    price: 4.5,
    stock: 220,
    featured: false,
    categorySlug: 'kitchen',
    image: DJ('groceries/tissue-paper-box'),
    tagSlugs: ['new'],
  },
  {
    sku: 'HD-004',
    slug: 'storage-box-set-3pc',
    nameAr: 'طقم صناديق تخزين — 3 قطع',
    nameEn: 'Storage Box Set 3pc',
    descriptionAr: 'صناديق بلاستيك شفافة بأغطية محكمة لتنظيم المطبخ والخزائن.',
    descriptionEn: 'Clear stackable storage boxes with lids.',
    price: 12.99,
    compareAtPrice: 15.99,
    stock: 48,
    featured: true,
    categorySlug: 'home-essentials',
    image: DJ('home-decoration/house-showpiece-plant'),
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'HD-005',
    slug: 'laundry-detergent-3kg',
    nameAr: 'مسحوق غسيل عائلي 3 كغ',
    nameEn: 'Family Laundry Detergent 3kg',
    descriptionAr: 'مسحوق غسيل للملابس البيضاء والملونة، مناسب للغسالات الأوتوماتيك.',
    descriptionEn: 'Laundry powder for colors and whites, suitable for automatic machines.',
    price: 8.75,
    compareAtPrice: 9.99,
    stock: 75,
    featured: true,
    categorySlug: 'cleaning',
    image: DJ('groceries/protein-powder'),
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'HD-006',
    slug: 'floor-cleaner-lavender-1l',
    nameAr: 'منظف أرضيات لافندر 1 لتر',
    nameEn: 'Lavender Floor Cleaner 1L',
    descriptionAr: 'منظف أرضيات يعطي لمعاناً ويُعطّر المكان برائحة اللافندر.',
    descriptionEn: 'Floor cleaner with lavender scent and shine.',
    price: 4.25,
    stock: 110,
    featured: false,
    categorySlug: 'cleaning',
    image: PICSUM('floor-cleaner'),
    tagSlugs: [],
  },
  {
    sku: 'HD-007',
    slug: 'bleach-white-1l',
    nameAr: 'مبيض ملابس 1 لتر',
    nameEn: 'Liquid Bleach 1L',
    descriptionAr: 'مبيض للتعقيم والتبييض — استخدم بحذر ووفق التعليمات على العبوة.',
    descriptionEn: 'Laundry bleach for whitening and disinfection. Use as directed.',
    price: 2.99,
    stock: 90,
    featured: false,
    categorySlug: 'cleaning',
    image: DJ('groceries/milk'),
    tagSlugs: [],
  },
  {
    sku: 'HD-008',
    slug: 'glass-cleaner-spray-500ml',
    nameAr: 'منظف زجاج بخاخ 500 مل',
    nameEn: 'Glass Cleaner Spray 500ml',
    descriptionAr: 'للنوافذ والمرايا والزجاج — بدون خطوط وبتركيبة سريعة التجفيف.',
    descriptionEn: 'Streak-free glass and mirror cleaner spray.',
    price: 3.5,
    stock: 130,
    featured: false,
    categorySlug: 'cleaning',
    image: PICSUM('glass-cleaner'),
    tagSlugs: ['new'],
  },
  {
    sku: 'HD-009',
    slug: 'trash-bags-large-30pc',
    nameAr: 'أكياس نفايات كبيرة — 30 حبة',
    nameEn: 'Large Trash Bags 30pc',
    descriptionAr: 'أكياس قوية مقاومة للتمزق، مناسبة للمنزل والمطبخ.',
    descriptionEn: 'Strong tear-resistant garbage bags.',
    price: 5.99,
    stock: 160,
    featured: false,
    categorySlug: 'home-essentials',
    image: PICSUM('trash-bags'),
    tagSlugs: [],
  },
  {
    sku: 'HD-010',
    slug: 'sponge-scrubber-6pack',
    nameAr: 'إسفنج تنظيف — 6 قطع',
    nameEn: 'Scrub Sponges 6-Pack',
    descriptionAr: 'إسفنج مزدوج الوجه للأواني والأسطح — يدوم لفترة أطول.',
    descriptionEn: 'Dual-sided scrub sponges for dishes and surfaces.',
    price: 2.75,
    stock: 200,
    featured: false,
    categorySlug: 'kitchen',
    image: PICSUM('sponges'),
    tagSlugs: ['new'],
  },
  {
    sku: 'HD-011',
    slug: 'aluminum-foil-30m',
    nameAr: 'ورق ألومنيوم 30 متر',
    nameEn: 'Aluminum Foil 30m',
    descriptionAr: 'لفة ألومنيوم للمطبخ — للتغليف والشواء والحفظ.',
    descriptionEn: 'Kitchen aluminum foil roll for wrapping and baking.',
    price: 3.25,
    stock: 140,
    featured: false,
    categorySlug: 'kitchen',
    image: PICSUM('aluminum-foil'),
    tagSlugs: [],
  },
  {
    sku: 'HD-012',
    slug: 'cling-film-30m',
    nameAr: 'نايلون تغليف طعام 30 متر',
    nameEn: 'Cling Film 30m',
    descriptionAr: 'نايلون لاصق للتغليف والحفظ في الثلاجة.',
    descriptionEn: 'Food wrap cling film for refrigerator storage.',
    price: 2.95,
    stock: 155,
    featured: false,
    categorySlug: 'kitchen',
    image: PICSUM('cling-film'),
    tagSlugs: [],
  },
  {
    sku: 'HD-013',
    slug: 'facial-tissues-200',
    nameAr: 'مناديل وجه — 200 منديل',
    nameEn: 'Facial Tissues 200 sheets',
    descriptionAr: 'مناديل ناعمة للوجه والمنزل، عبوة اقتصادية.',
    descriptionEn: 'Soft facial tissues, family pack.',
    price: 3.99,
    stock: 190,
    featured: true,
    categorySlug: 'bathroom',
    image: DJ('groceries/tissue-paper-box'),
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'HD-014',
    slug: 'hand-soap-liquid-500ml',
    nameAr: 'صابون سائل لليدين 500 مل',
    nameEn: 'Liquid Hand Soap 500ml',
    descriptionAr: 'صابون سائل مرطب برائحة خفيفة، مناسب لجميع أفراد العائلة.',
    descriptionEn: 'Moisturizing liquid hand soap for daily use.',
    price: 4.75,
    stock: 120,
    featured: false,
    categorySlug: 'bathroom',
    image: DJ('groceries/honey-jar'),
    tagSlugs: ['new'],
  },
  {
    sku: 'HD-015',
    slug: 'paper-towels-2-roll',
    nameAr: 'مناديل ورقية — لفتاين كبيرتان',
    nameEn: 'Paper Towels 2 Large Rolls',
    descriptionAr: 'لفائف كبيرة للمطبخ — امتصاص عالي.',
    descriptionEn: 'Large kitchen paper towel rolls.',
    price: 5.5,
    compareAtPrice: 6.25,
    stock: 85,
    featured: false,
    categorySlug: 'kitchen',
    image: DJ('groceries/eggs'),
    tagSlugs: [],
  },
  {
    sku: 'HD-016',
    slug: 'dish-brush-with-handle',
    nameAr: 'فرشاة جلي بمقبض',
    nameEn: 'Dish Brush with Handle',
    descriptionAr: 'فرشاة لتنظيف الأواني والقدور بسهولة.',
    descriptionEn: 'Dish brush with comfortable grip handle.',
    price: 2.25,
    stock: 175,
    featured: false,
    categorySlug: 'kitchen',
    image: PICSUM('dish-brush'),
    tagSlugs: [],
  },
  {
    sku: 'HD-017',
    slug: 'food-containers-5pc',
    nameAr: 'علب حفظ طعام — 5 قطع',
    nameEn: 'Food Storage Containers 5pc',
    descriptionAr: 'علب بلاستيك آمنة للميكروويف والثلاجة بأحجام مختلفة.',
    descriptionEn: 'Microwave-safe food containers in assorted sizes.',
    price: 9.99,
    stock: 62,
    featured: true,
    categorySlug: 'kitchen',
    image: DJ('home-decoration/plant-pot'),
    tagSlugs: ['new'],
  },
  {
    sku: 'HD-018',
    slug: 'plastic-cups-50pc',
    nameAr: 'أكواب بلاستيك — 50 حبة',
    nameEn: 'Disposable Plastic Cups 50pc',
    descriptionAr: 'أكواب للمناسبات والضيافة — حجم 200 مل تقريباً.',
    descriptionEn: 'Disposable cups for parties and gatherings.',
    price: 4.5,
    stock: 98,
    featured: false,
    categorySlug: 'kitchen',
    image: DJ('groceries/water'),
    tagSlugs: [],
  },
  {
    sku: 'HD-019',
    slug: 'air-freshener-lavender',
    nameAr: 'معطر جو لافندر 300 مل',
    nameEn: 'Lavender Air Freshener 300ml',
    descriptionAr: 'معطر للغرف والحمام — رائحة لافندر هادئة.',
    descriptionEn: 'Room spray air freshener, lavender scent.',
    price: 5.25,
    stock: 88,
    featured: false,
    categorySlug: 'bathroom',
    image: PICSUM('air-freshener'),
    tagSlugs: [],
  },
  {
    sku: 'HD-020',
    slug: 'microfiber-mop',
    nameAr: 'ممسحة مايكروفايبر مع عصا',
    nameEn: 'Microfiber Mop with Handle',
    descriptionAr: 'ممسحة عملية للأرضيات الرخام والباركيه والسيراميك.',
    descriptionEn: 'Microfiber mop for tile and hard floors.',
    price: 14.5,
    compareAtPrice: 17.99,
    stock: 35,
    featured: true,
    categorySlug: 'home-essentials',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'HD-021',
    slug: 'rice-basmati-2kg',
    nameAr: 'أرز بسمتي 2 كغ',
    nameEn: 'Basmati Rice 2kg',
    descriptionAr: 'أرز بسمتي طويل الحبة — مناسب للمناسبات واليومي.',
    descriptionEn: 'Long grain basmati rice, 2kg bag.',
    price: 6.99,
    stock: 150,
    featured: false,
    categorySlug: 'kitchen',
    image: DJ('groceries/rice'),
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'HD-022',
    slug: 'cooking-oil-1l',
    nameAr: 'زيت نباتي للطبخ 1 لتر',
    nameEn: 'Cooking Oil 1L',
    descriptionAr: 'زيت نباتي متعدد الاستخدامات للقلي والطبخ.',
    descriptionEn: 'All-purpose vegetable cooking oil.',
    price: 5.75,
    stock: 125,
    featured: false,
    categorySlug: 'kitchen',
    image: DJ('groceries/cooking-oil'),
    tagSlugs: [],
  },
  {
    sku: 'HD-023',
    slug: 'nescafe-classic-200g',
    nameAr: 'نسكافيه كلاسيك 200 غ',
    nameEn: 'Nescafe Classic 200g',
    descriptionAr: 'قهوة سريعة التحضير — العبوة الأصلية 200 غرام.',
    descriptionEn: 'Instant coffee jar 200g.',
    price: 11.5,
    compareAtPrice: 12.99,
    stock: 70,
    featured: true,
    categorySlug: 'kitchen',
    image: DJ('groceries/nescafe-coffee'),
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'HD-024',
    slug: 'soft-drinks-mix-6pack',
    nameAr: 'مشروبات غازية — عبوة 6',
    nameEn: 'Soft Drinks 6-Pack',
    descriptionAr: 'عبوة عائلية من المشروبات الغازية — مثالية للضيافة.',
    descriptionEn: 'Assorted soft drinks family pack.',
    price: 7.25,
    stock: 95,
    featured: false,
    categorySlug: 'kitchen',
    image: DJ('groceries/soft-drinks'),
    tagSlugs: ['new'],
  },
];

export function productImageFallback(slug: string): string {
  return PICSUM(slug);
}
