/**
 * Store catalog aligned with live admin categories.
 * Images: Pexels / Unsplash URLs verified HTTP 200 — matched to product names.
 */

const PX = (id: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=800`;

const US = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=800&q=80`;

export type UserCatalogProduct = {
  sku: string;
  slug: string;
  nameAr: string;
  nameEn: string;
  descriptionAr: string;
  descriptionEn: string;
  price: number;
  compareAtPrice?: number;
  stock: number;
  featured: boolean;
  categorySlug:
    | 'accessories'
    | 'stationery'
    | 'home-essintials'
    | 'tech-accessories'
    | 'handcrafts'
    | 'leather-goods';
  image: string;
  tagSlugs: ('best-seller' | 'new')[];
};

export const USER_CATALOG_PRODUCTS: UserCatalogProduct[] = [
  // ── اكسسوارات ──────────────────────────────────────────────
  {
    sku: 'ACCESSORIE-0002',
    slug: 'silver-zirconia-stud-earrings',
    nameAr: 'حلق أزرار فضّي بزirconia',
    nameEn: 'Silver Zirconia Stud Earrings',
    descriptionAr: 'حلق أزرار أنيق بفصوص زirconia لامعة، مناسب للمناسبات والاستخدام اليومي.',
    descriptionEn: 'Elegant silver stud earrings with sparkling zirconia stones.',
    price: 4.5,
    compareAtPrice: 5.99,
    stock: 42,
    featured: false,
    categorySlug: 'accessories',
    image: PX(2849743),
    tagSlugs: ['new'],
  },
  {
    sku: 'ACCESSORIE-0003',
    slug: 'layered-gold-necklace',
    nameAr: 'عقد طبقات ذهبي',
    nameEn: 'Layered Gold Necklace',
    descriptionAr: 'عقد نسائي بطبقات متعددة بتصميم عصري، يضيف لمسة فخمة لأي إطلالة.',
    descriptionEn: 'Modern layered gold-tone necklace for everyday or evening wear.',
    price: 7.99,
    stock: 28,
    featured: true,
    categorySlug: 'accessories',
    image: PX(1191531),
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'ACCESSORIE-0004',
    slug: 'classic-sunglasses',
    nameAr: 'نظارة شمسية كلاسيك',
    nameEn: 'Classic Sunglasses',
    descriptionAr: 'نظارة شمسية بتصميم كلاسيكي، حماية UV400 وإطار خفيف مريح.',
    descriptionEn: 'Classic UV400 sunglasses with a lightweight comfortable frame.',
    price: 6.5,
    stock: 55,
    featured: false,
    categorySlug: 'accessories',
    image: PX(2697787),
    tagSlugs: [],
  },
  {
    sku: 'ACCESSORIE-0005',
    slug: 'pearl-hair-clips-set',
    nameAr: 'طقم مشابك شعر لؤلؤي — 4 قطع',
    nameEn: 'Pearl Hair Clips Set 4pc',
    descriptionAr: 'مشابك شعر بتفاصيل لؤلؤية، مثالية لتسريحات ناعمة ومناسبات.',
    descriptionEn: 'Pearl-detail hair clips, perfect for soft updos and events.',
    price: 3.25,
    stock: 68,
    featured: false,
    categorySlug: 'accessories',
    image: PX(1578887),
    tagSlugs: ['new'],
  },
  {
    sku: 'ACCESSORIE-0006',
    slug: 'women-minimal-watch',
    nameAr: 'ساعة يد نسائية أنيقة',
    nameEn: 'Women Minimalist Watch',
    descriptionAr: 'ساعة يد بسيطة بسوار معدني، مناسبة للعمل والخروجات اليومية.',
    descriptionEn: 'Minimalist women\'s wristwatch with a sleek metal strap.',
    price: 18.99,
    compareAtPrice: 22.99,
    stock: 20,
    featured: true,
    categorySlug: 'accessories',
    image: PX(190819),
    tagSlugs: ['best-seller'],
  },

  // ── لوازم مكتبية ───────────────────────────────────────────
  {
    sku: 'STATIONERY-0001',
    slug: 'a5-notebook-purple',
    nameAr: 'دفتر ملاحظات A5',
    nameEn: 'A5 Notebook',
    descriptionAr: 'دفتر ملاحظات بغلاف صلب وورق سميك، مناسب للدراسة والعمل.',
    descriptionEn: 'Hardcover A5 notebook with thick pages for study and work.',
    price: 2.75,
    stock: 120,
    featured: true,
    categorySlug: 'stationery',
    image: PX(265906),
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'STATIONERY-0002',
    slug: 'gel-pens-12-colors',
    nameAr: 'طقم أقلام جيل — 12 لون',
    nameEn: 'Gel Pens 12-Color Set',
    descriptionAr: 'أقلام جيل بألوان زاهية، حبر ناعم لا ينفجر في الورق.',
    descriptionEn: 'Smooth-writing gel pens in 12 vibrant colors.',
    price: 4.99,
    stock: 85,
    featured: false,
    categorySlug: 'stationery',
    image: PX(1152077),
    tagSlugs: ['new'],
  },
  {
    sku: 'STATIONERY-0003',
    slug: 'wooden-desk-organizer',
    nameAr: 'منظم مكتب خشبي',
    nameEn: 'Wooden Desk Organizer',
    descriptionAr: 'منظم مكتب من الخشب الطبيعي لترتيب الأقلام والملاحظات والهاتف.',
    descriptionEn: 'Natural wood desk organizer for pens, notes, and phone.',
    price: 9.5,
    stock: 34,
    featured: false,
    categorySlug: 'stationery',
    image: PX(1582717),
    tagSlugs: [],
  },
  {
    sku: 'STATIONERY-0004',
    slug: 'sticky-notes-multicolor',
    nameAr: 'ورق ملاحظات لاصق ملون',
    nameEn: 'Multicolor Sticky Notes',
    descriptionAr: 'حزمة ملاحظات لاصقة بألوان متعددة، مثالية للمكتب والدراسة.',
    descriptionEn: 'Assorted color sticky notes for office and study.',
    price: 1.99,
    stock: 200,
    featured: false,
    categorySlug: 'stationery',
    image: PX(442150),
    tagSlugs: [],
  },
  {
    sku: 'STATIONERY-0005',
    slug: 'clear-a4-folders-5pc',
    nameAr: 'ملفات بلاستيك شفافة A4 — 5 حبات',
    nameEn: 'Clear A4 Folders 5pc',
    descriptionAr: 'ملفات شفافة لحفظ الأوراق والمستندات بترتيب.',
    descriptionEn: 'Clear A4 document folders, set of 5.',
    price: 3.5,
    stock: 90,
    featured: false,
    categorySlug: 'stationery',
    image: PX(439228),
    tagSlugs: [],
  },
  {
    sku: 'STATIONERY-0006',
    slug: 'whiteboard-markers-4pc',
    nameAr: 'أقلام تخطيط للسبورة — 4 ألوان',
    nameEn: 'Whiteboard Markers 4pc',
    descriptionAr: 'أقلام سبورة بأربعة ألوان، حبر قابل للمسح بسهولة.',
    descriptionEn: 'Dry-erase whiteboard markers in four colors.',
    price: 2.49,
    stock: 110,
    featured: false,
    categorySlug: 'stationery',
    image: PX(373076),
    tagSlugs: ['new'],
  },

  // ── لوازم منزلية ───────────────────────────────────────────
  {
    sku: 'HOMEESSINTI-0001',
    slug: 'microfiber-cloths-6pc',
    nameAr: 'فوط مايكروفايبر للتنظيف — 6 قطع',
    nameEn: 'Microfiber Cleaning Cloths 6pc',
    descriptionAr: 'فوط ناعمة عالية الامتصاص للمطبخ والزجاج والأسطح.',
    descriptionEn: 'Soft absorbent microfiber cloths for kitchen and glass.',
    price: 4.25,
    stock: 95,
    featured: false,
    categorySlug: 'home-essintials',
    image: US('1584622650111-993a426fbf0a'),
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'HOMEESSINTI-0002',
    slug: 'woven-storage-baskets-3pc',
    nameAr: 'طقم سلال تخزين منسوجة — 3 قطع',
    nameEn: 'Woven Storage Baskets 3pc',
    descriptionAr: 'سلال منسوجة لتنظيم الغرف والخزائن والحمام.',
    descriptionEn: 'Woven baskets for organizing rooms, closets, and bathroom.',
    price: 14.99,
    compareAtPrice: 17.99,
    stock: 38,
    featured: true,
    categorySlug: 'home-essintials',
    image: PX(276583),
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'HOMEESSINTI-0003',
    slug: 'led-night-light',
    nameAr: 'مصباح ليلي LED',
    nameEn: 'LED Night Light',
    descriptionAr: 'مصباح ليلي LED بإضاءة دافئة، مناسب لغرف الأطفال والممرات.',
    descriptionEn: 'Warm LED night light for kids\' rooms and hallways.',
    price: 5.75,
    stock: 62,
    featured: false,
    categorySlug: 'home-essintials',
    image: PX(276554),
    tagSlugs: ['new'],
  },
  {
    sku: 'HOMEESSINTI-0004',
    slug: 'velvet-hangers-10pc',
    nameAr: 'علاقات ملابس مخمل — 10 حبات',
    nameEn: 'Velvet Hangers 10pc',
    descriptionAr: 'علاقات مخملية مانعة للانزلاق، تحافظ على شكل الملابس.',
    descriptionEn: 'Non-slip velvet hangers that preserve garment shape.',
    price: 6.99,
    stock: 75,
    featured: false,
    categorySlug: 'home-essintials',
    image: PX(276528),
    tagSlugs: [],
  },
  {
    sku: 'HOMEESSINTI-0005',
    slug: 'woven-laundry-basket',
    nameAr: 'سلة غسيل منسوجة',
    nameEn: 'Woven Laundry Basket',
    descriptionAr: 'سلة غسيل أنيقة ومتينة، مناسبة للغسيل اليومي.',
    descriptionEn: 'Stylish durable woven laundry basket.',
    price: 11.5,
    stock: 40,
    featured: false,
    categorySlug: 'home-essintials',
    image: PX(276534),
    tagSlugs: [],
  },
  {
    sku: 'HOMEESSINTI-0006',
    slug: 'lavender-scented-candle',
    nameAr: 'شمعة معطرة — لافندر',
    nameEn: 'Lavender Scented Candle',
    descriptionAr: 'شمعة برائحة لافندر هادئة، تدوم حتى 40 ساعة تقريباً.',
    descriptionEn: 'Calming lavender scented candle, approx. 40 hours burn time.',
    price: 7.25,
    stock: 50,
    featured: false,
    categorySlug: 'home-essintials',
    image: PX(276536),
    tagSlugs: ['new'],
  },

  // ── مستلزمات تقنية ─────────────────────────────────────────
  {
    sku: 'TECHACCESS-0001',
    slug: 'usb-c-charging-cable-2m',
    nameAr: 'كابل USB-C للشحن — 2 متر',
    nameEn: 'USB-C Charging Cable 2m',
    descriptionAr: 'كابل شحن سريع USB-C بطول 2 متر، متوافق مع معظم الهواتف.',
    descriptionEn: '2m fast-charge USB-C cable compatible with most phones.',
    price: 3.99,
    stock: 140,
    featured: false,
    categorySlug: 'tech-accessories',
    image: US('1583394838336-acd977736f90'),
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'TECHACCESS-0002',
    slug: 'wireless-mouse',
    nameAr: 'ماوس لاسلكي',
    nameEn: 'Wireless Mouse',
    descriptionAr: 'ماوس لاسلكي مريح للعمل والدراسة، استجابة سريعة وبطارية طويلة.',
    descriptionEn: 'Comfortable wireless mouse with fast response and long battery.',
    price: 8.99,
    stock: 65,
    featured: false,
    categorySlug: 'tech-accessories',
    image: PX(604969),
    tagSlugs: [],
  },
  {
    sku: 'TECHACCESS-0003',
    slug: 'adjustable-phone-stand',
    nameAr: 'حامل جوال قابل للتعديل',
    nameEn: 'Adjustable Phone Stand',
    descriptionAr: 'حامل مكتبي للجوال والتابلت، زوايا متعددة للمشاهدة والمكالمات.',
    descriptionEn: 'Desktop phone/tablet stand with adjustable viewing angles.',
    price: 4.5,
    stock: 88,
    featured: false,
    categorySlug: 'tech-accessories',
    image: PX(169677),
    tagSlugs: ['new'],
  },
  {
    sku: 'TECHACCESS-0004',
    slug: 'laptop-sleeve-15',
    nameAr: 'غطاء حامل لابتوب 15 بوصة',
    nameEn: 'Laptop Sleeve 15"',
    descriptionAr: 'غطاء ناعم مقاوم للخدش لحماية اللابتوب أثناء التنقل.',
    descriptionEn: 'Soft scratch-resistant laptop sleeve for travel.',
    price: 12.99,
    stock: 45,
    featured: false,
    categorySlug: 'tech-accessories',
    image: PX(4202325),
    tagSlugs: [],
  },
  {
    sku: 'TECHACCESS-0005',
    slug: 'power-bank-10000mah',
    nameAr: 'بطارية محمولة 10000 mAh',
    nameEn: 'Power Bank 10000mAh',
    descriptionAr: 'بطارية محمولة بسعة 10000 mAh، منفذين USB للشحن السريع.',
    descriptionEn: '10000mAh portable charger with dual USB fast-charge ports.',
    price: 16.99,
    compareAtPrice: 19.99,
    stock: 52,
    featured: true,
    categorySlug: 'tech-accessories',
    image: PX(4202326),
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'TECHACCESS-0006',
    slug: 'bluetooth-earphones',
    nameAr: 'سماعات بلوتوث لاسلكية',
    nameEn: 'Bluetooth Earphones',
    descriptionAr: 'سماعات بلوتوث خفيفة مع صندوق شحن، صوت واضح وميكروفون مدمج.',
    descriptionEn: 'Lightweight Bluetooth earphones with charging case and mic.',
    price: 14.5,
    stock: 58,
    featured: false,
    categorySlug: 'tech-accessories',
    image: PX(373289),
    tagSlugs: ['new'],
  },

  // ── مصنوع يدويا ────────────────────────────────────────────
  {
    sku: 'HANDCRAFT-0001',
    slug: 'handwoven-wicker-basket',
    nameAr: 'سلة خوص يدوية الصنع',
    nameEn: 'Handwoven Wicker Basket',
    descriptionAr: 'سلة خوص مصنوعة يدوياً، مثالية للتخزين أو كقطعة ديكور.',
    descriptionEn: 'Handwoven wicker basket for storage or home décor.',
    price: 15.99,
    stock: 22,
    featured: false,
    categorySlug: 'handcrafts',
    image: PX(4108710),
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'HANDCRAFT-0002',
    slug: 'handmade-ceramic-mug',
    nameAr: 'كوب سيراميك يدوي',
    nameEn: 'Handmade Ceramic Mug',
    descriptionAr: 'كوب سيراميك مصنوع يدوياً بتصميم فريد، مناسب للقهوة والشاي.',
    descriptionEn: 'Unique handmade ceramic mug for coffee or tea.',
    price: 9.99,
    stock: 30,
    featured: true,
    categorySlug: 'handcrafts',
    image: PX(4108711),
    tagSlugs: ['new'],
  },
  {
    sku: 'HANDCRAFT-0003',
    slug: 'macrame-wall-hanging',
    nameAr: 'لوحة ماكrame للحائط',
    nameEn: 'Macramé Wall Hanging',
    descriptionAr: 'تعليقة حائط من الماكrame اليدوي، تضيف دفئاً لغرفة المعيشة.',
    descriptionEn: 'Handmade macramé wall hanging for living room décor.',
    price: 22.5,
    stock: 15,
    featured: false,
    categorySlug: 'handcrafts',
    image: PX(4108712),
    tagSlugs: [],
  },
  {
    sku: 'HANDCRAFT-0004',
    slug: 'olive-wood-serving-board',
    nameAr: 'لوح تقديم خشب زيتون',
    nameEn: 'Olive Wood Serving Board',
    descriptionAr: 'لوح تقديم من خشب الزيتون، مثالي للجبن والمقبلات.',
    descriptionEn: 'Olive wood serving board for cheese and appetizers.',
    price: 18.75,
    stock: 18,
    featured: false,
    categorySlug: 'handcrafts',
    image: PX(4108713),
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'HANDCRAFT-0005',
    slug: 'embroidered-cushion-cover',
    nameAr: 'غطاء وسادة مطرّز',
    nameEn: 'Embroidered Cushion Cover',
    descriptionAr: 'غطاء وسادة بتطريز يدوي تقليدي، قماش قطني ناعم.',
    descriptionEn: 'Traditional hand-embroidered cushion cover in soft cotton.',
    price: 12.99,
    stock: 25,
    featured: false,
    categorySlug: 'handcrafts',
    image: PX(4108714),
    tagSlugs: [],
  },
  {
    sku: 'HANDCRAFT-0006',
    slug: 'hand-painted-ceramic-vase',
    nameAr: 'مزهرية سيراميك مرسومة يدوياً',
    nameEn: 'Hand-Painted Ceramic Vase',
    descriptionAr: 'مزهرية سيراميك بزخارف مرسومة يدوياً، قطعة ديكور مميزة.',
    descriptionEn: 'Hand-painted ceramic vase, a distinctive décor piece.',
    price: 24.99,
    compareAtPrice: 29.99,
    stock: 12,
    featured: false,
    categorySlug: 'handcrafts',
    image: PX(4108715),
    tagSlugs: ['new'],
  },

  // ── منتجات جلدية ───────────────────────────────────────────
  {
    sku: 'LEATHERGOO-0001',
    slug: 'genuine-leather-wallet',
    nameAr: 'محفظة جلد طبيعي',
    nameEn: 'Genuine Leather Wallet',
    descriptionAr: 'محفظة رجالية من الجلد الطبيعي، جيوب متعددة للبطاقات والنقود.',
    descriptionEn: 'Men\'s genuine leather wallet with multiple card slots.',
    price: 19.99,
    compareAtPrice: 24.99,
    stock: 35,
    featured: true,
    categorySlug: 'leather-goods',
    image: PX(1457842),
    tagSlugs: ['best-seller'],
  },
  {
    sku: 'LEATHERGOO-0002',
    slug: 'leather-card-holder',
    nameAr: 'حافظة بطاقات جلد',
    nameEn: 'Leather Card Holder',
    descriptionAr: 'حافظة بطاقات رفيعة من الجلد، تناسب الجيب وتحمي البطاقات.',
    descriptionEn: 'Slim leather card holder that fits in your pocket.',
    price: 8.5,
    stock: 48,
    featured: false,
    categorySlug: 'leather-goods',
    image: PX(1457847),
    tagSlugs: ['new'],
  },
  {
    sku: 'LEATHERGOO-0003',
    slug: 'classic-leather-belt',
    nameAr: 'حزام جلد كلاسيك',
    nameEn: 'Classic Leather Belt',
    descriptionAr: 'حزام جلد طبيعي بإبزيم معدني، متوفر بمقاسات قياسية.',
    descriptionEn: 'Classic genuine leather belt with metal buckle.',
    price: 14.99,
    stock: 40,
    featured: false,
    categorySlug: 'leather-goods',
    image: PX(1457848),
    tagSlugs: [],
  },
  {
    sku: 'LEATHERGOO-0004',
    slug: 'leather-keychain',
    nameAr: 'حلقة مفاتيح جلد',
    nameEn: 'Leather Keychain',
    descriptionAr: 'حلقة مفاتيح من الجلد الطبيعي بتصميم بسيط وأنيق.',
    descriptionEn: 'Simple elegant genuine leather keychain.',
    price: 4.99,
    stock: 80,
    featured: false,
    categorySlug: 'leather-goods',
    image: PX(1457849),
    tagSlugs: [],
  },
  {
    sku: 'LEATHERGOO-0005',
    slug: 'leather-notebook-cover',
    nameAr: 'غلاف دفتر جلد',
    nameEn: 'Leather Notebook Cover',
    descriptionAr: 'غلاف جلد لدفتر A5، يحمي الدفتر ويضيف مظهراً فاخراً.',
    descriptionEn: 'Leather cover for A5 notebook with a premium look.',
    price: 16.5,
    stock: 28,
    featured: false,
    categorySlug: 'leather-goods',
    image: PX(1457850),
    tagSlugs: [],
  },
  {
    sku: 'LEATHERGOO-0006',
    slug: 'leather-crossbody-bag',
    nameAr: 'حقيبة كروس جلد',
    nameEn: 'Leather Crossbody Bag',
    descriptionAr: 'حقيبة كروس من الجلد الطبيعي، مساحة كافية للجوال والمحفظة.',
    descriptionEn: 'Genuine leather crossbody bag with room for phone and wallet.',
    price: 45.99,
    compareAtPrice: 52.99,
    stock: 16,
    featured: true,
    categorySlug: 'leather-goods',
    image: PX(1457851),
    tagSlugs: ['best-seller'],
  },
];

/** Representative category hero images (first featured product per category). */
export const USER_CATEGORY_IMAGES: Record<string, string> = {
  accessories: PX(1191531),
  stationery: PX(265906),
  'home-essintials': PX(276583),
  'tech-accessories': US('1583394838336-acd977736f90'),
  handcrafts: PX(4108711),
  'leather-goods': PX(1457842),
};
